switch:
	darwin-rebuild switch --flake ~/dotfiles/nix-darwin/.config/nix-darwin

test:
	darwin-rebuild test --flake ~/dotfiles/nix-darwin/.config/nix-darwin

update:
	nix flake update --flake ~/dotfiles/nix-darwin/.config/nix-darwin

